export const ATTRIBUTE_TYPES = {
  VIEW_ANALYTICS: "VIEW_ANALYTICS",
  MANAGE_PROJECTS: "MANAGE_PROJECTS",
  MANAGE_USERS: "MANAGE_USERS",
  SYSTEM_SETTINGS: "SYSTEM_SETTINGS",
} as const;

export type AttributeType = keyof typeof ATTRIBUTE_TYPES;
